version: '3'
services:
  website:
    container_name: 'website'
    restart: on-failure
    build: 
      context: ./website
      dockerfile: Dockerfile
    environment:
      - EC2_HOST_DNS=${EC2_HOST_DNS}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_NODE_ENV=${REACT_APP_NODE_ENV}
    ports:
      - "3000:3000"
    volumes:
      - website:/website/build/  # build files will be added at this directory
  
  nginx:
    container_name: 'nginx'
    restart: on-failure
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    environment:
      - EC2_HOST_DNS=${EC2_HOST_DNS}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_NODE_ENV=${REACT_APP_NODE_ENV}
    ports:
      - "80:80"
    volumes:
      - website:/usr/share/nginx/html/website # Copy React App's build files to the Nginx directory
    depends_on:
      - website

volumes:
  website: